CREATE TABLE `z09_DataStore`.`TaskIO` ( 
`AttemptId` TEXT NOT NULL , 
`SubjectId` TEXT NULL DEFAULT NULL ,
`SessionId` INT NULL DEFAULT NULL ,
`SequenceId` TEXT NULL DEFAULT NULL ,
`TrialId` INT NULL DEFAULT NULL ,
`Run` TEXT NULL DEFAULT NULL , 
`AttemptNum` INT NULL DEFAULT NULL ,
`FieldIdx_C` INT NULL DEFAULT NULL , 
`FieldIdx_R` INT NULL DEFAULT NULL ,
`Correct` BOOLEAN NULL DEFAULT NULL ,
`RT` INT NULL DEFAULT NULL , 
`DateTime_Write` DATETIME NULL DEFAULT NULL , 
PRIMARY KEY (`AttemptId`(32))) ENGINE = MyISAM;