CREATE TABLE `z09_DataStore`.`Register` ( 
`SubjectId` TEXT NOT NULL ,
`SeqAFirst` BOOLEAN NULL DEFAULT NULL ,
`ImgAFirst` BOOLEAN NULL DEFAULT NULL ,
`ImgPermA` TEXT NULL DEFAULT NULL ,
`ImgPermB` TEXT NULL DEFAULT NULL ,
PRIMARY KEY (`SubjectId`(8))) ENGINE = MyISAM;